ead:
  serviceRegistry:
    username: admin
    password: 'admin'
  auth:
    jwtSecret: gVkYp3s6v9y$B&E)H@McQfThWmZq4t7w!z%C*F-JaNdRgUkXn2r5u8x/A?D(G+Kb
    jwtExpirationMs: 14400000

eureka:
  client:
    service-url:
      defaultZone:  ${EUREKA_URL:http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka}
  instance:
    hostname: localhost
    instanceId : ${spring.application.name}:${random.value}
    metadata-map:
      #Integrated into Prometheus, the following data will be added to the tags before the Prometheus re tag, for example, sys. Module will become
      "prometheus.scrape": "true"
      "prometheus.path": "/ead-authuser/actuator/prometheus"
      "sys.module": "order"
    statusPageUrlPath: ${server.servlet.context-path}actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}actuator/health